CREATE TABLE admin_analytics_daily_summary (
    property_id_hash CHAR(64) NOT NULL,
    report_date DATE NOT NULL,
    report_timezone VARCHAR(64) NOT NULL,
    active_users BIGINT NOT NULL DEFAULT 0,
    total_users BIGINT NOT NULL DEFAULT 0,
    new_users BIGINT NOT NULL DEFAULT 0,
    sessions BIGINT NOT NULL DEFAULT 0,
    engaged_sessions BIGINT NOT NULL DEFAULT 0,
    views BIGINT NOT NULL DEFAULT 0,
    event_count BIGINT NOT NULL DEFAULT 0,
    key_events DECIMAL(20,6) NOT NULL DEFAULT 0,
    engagement_seconds DECIMAL(20,3) NOT NULL DEFAULT 0,
    data_status VARCHAR(16) NOT NULL DEFAULT 'PROVISIONAL',
    collected_at TIMESTAMP(6) NOT NULL,
    finalized_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (property_id_hash, report_date)
);

CREATE TABLE admin_analytics_daily_breakdown (
    property_id_hash CHAR(64) NOT NULL,
    report_date DATE NOT NULL,
    breakdown_type VARCHAR(32) NOT NULL,
    dimension_hash CHAR(64) NOT NULL,
    dimension_value TEXT NOT NULL,
    dimension_label VARCHAR(512) NOT NULL,
    dimension_detail VARCHAR(512) NULL,
    active_users BIGINT NOT NULL DEFAULT 0,
    total_users BIGINT NOT NULL DEFAULT 0,
    new_users BIGINT NOT NULL DEFAULT 0,
    sessions BIGINT NOT NULL DEFAULT 0,
    engaged_sessions BIGINT NOT NULL DEFAULT 0,
    views BIGINT NOT NULL DEFAULT 0,
    event_count BIGINT NOT NULL DEFAULT 0,
    key_events DECIMAL(20,6) NOT NULL DEFAULT 0,
    engagement_seconds DECIMAL(20,3) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (property_id_hash, report_date, breakdown_type, dimension_hash),
    CONSTRAINT fk_daily_breakdown_summary FOREIGN KEY (property_id_hash, report_date)
        REFERENCES admin_analytics_daily_summary (property_id_hash, report_date) ON DELETE CASCADE
);

CREATE TABLE admin_analytics_collection_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id_hash CHAR(64) NOT NULL,
    target_date DATE NOT NULL,
    range_start DATE NOT NULL,
    range_end DATE NOT NULL,
    run_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6) NULL,
    api_request_count INT NOT NULL DEFAULT 0,
    stored_row_count INT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    quota_json JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
